version: "3"

services:
  api:
    build: .
    image: $DOCKER_IMAGE
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 3000:80
    restart: always
